#!/bin/bash
# Yanhua Liu ytz2 assignment 1 for cs820
# Sep 10, 2013

# print the status
function print_status {
echo "EXIT STATUS:"
if [ "$1" == "0" ]; then
	echo "SUCCESS"
else
	echo "FAILURE"
fi
}  

echo "Yanhua Liu (ytz2)"
echo "Tests for CS820 Assignment1"
echo
echo "Test Under Enviroment:"
uname
echo
echo
echo "The EXIT STATUS DEFINITION: 0 SUCCESS, OTHERS FAILURE"
echo 
echo
path=$(pwd)

mkdir ./dir
mkdir ./dir/A
mkdir ./dir/B
mkdir ./dir/.A
cp ./test000.in ./dir
cp ./test001.in ./dir
cp ./test000.in ./dir/A
cp ./test001.in ./dir/B
cp ./test000.in ./dir/.A/.test000.in
mkdir ./dir/A/A
mkdir ./dir/A/B
mkdir ./dir/B/A
mkdir ./dir/B/B
cp ./test000.in ./dir/A/A
cp ./test001.in ./dir/A/B
cp ./test000.in ./dir/B/A
cp ./test001.in ./dir/B/B
mkdir ./dir/A/A/A
mkdir ./dir/A/A/B
mkdir ./dir/B/B/A
mkdir ./dir/B/B/B
cp ./test000.in ./dir/A/A/A
cp ./test001.in ./dir/A/A/B
cp ./test000.in ./dir/B/B/A
cp ./test001.in ./dir/B/B/B

cp -rf dir dir2

ln -s $path/dir  ./dir/A/A/A/symtest1
ln -s noexit ./dir/B/B/B/symtest2
ln -s $path/test000.in ./dir/A/B/symtest3


ln -s $path/dir2  ./dir2/A/A/A/symtest1
ln -s noexit ./dir2/B/B/B/symtest2
ln -s $path/test000.in ./dir2/A/B/symtest3

echo "The test file and directory structure"
echo "   |-test000.in"
echo "   |-test001.in"
echo "   |-test002.in"
find ./dir -print | sed -e '/^\.$/d' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
find ./dir2 -print | sed -e '/^\.$/d' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
echo 
echo "Notes:"
ls -l  ./dir/A/A/A/symtest1
ls -l ./dir/B/B/B/symtest2
ls -l ./dir/A/B/symtest3

ls -l  ./dir2/A/A/A/symtest1
ls -l  ./dir2/B/B/B/symtest2
ls -l  ./dir2/A/B/symtest3

make

./plcs -t0 -n2 -p -a -f -t10 -d2 This dir
make clean
rm -rf dir
rm -rf dir2