#!/bin/bash
# Yanhua Liu ytz2 assignment 1 for cs820
# Sep 10, 2013

# print the status
function print_status {
echo "EXIT STATUS:"
if [ "$1" == "0" ]; then
	echo "SUCCESS"
else
	echo "FAILURE"
fi
}  

echo "Yanhua Liu (ytz2)"
echo "Tests for CS820 Assignment1"
echo
echo "Test Under Enviroment:"
uname
echo
echo "Setting up the testing input"
path=$(pwd)

make clean
make
mkdir ./testdir1
cp ./test000.in ./testdir1
cp ./test001.in ./testdir1
cp ./test001.in ./testdir1/.test001.in
mkdir ./testdir1/testdir1_dir1
cp ./test000.in ./testdir1/testdir1_dir1
cp ./test001.in ./testdir1/testdir1_dir1
mkdir ./testdir1/testdir1_dir2
mkdir ./testdir1/testdir1_dir1/testdir1_dir1_dir1
mkdir ./testdir1/testdir1_dir1/testdir1_dir1_dir2
mkdir ./testdir1/testdir1_dir1/testdir1_dir1_dir1/testdir1_dir1_dir1_dir1
cp ./test000.in ./testdir1/testdir1_dir1/testdir1_dir1_dir1/testdir1_dir1_dir1_dir1
cp ./test001.in  ./testdir1/testdir1_dir2
ln -s $path/testdir1 ./testdir1/testdir1_dir1/testdir1_dir1_dir1/testdir1_dir1_dir1_dir1/symtest1
ln -s noexit ./testdir1/testdir1_dir1/testdir1_dir1_dir1/testdir1_dir1_dir1_dir1/symtest2
mkdir ./testdir1/testdir1_dir2/testdir1_dir2_dir1
mkdir ./testdir1/testdir1_dir2/testdir1_dir2_dir2
cp ./test000.in ./testdir1/testdir1_dir2/testdir1_dir2_dir1
cp ./test001.in ./testdir1/testdir1_dir2/testdir1_dir2_dir2

mkdir ./testdir2
cp ./test000.in ./testdir2
cp ./test001.in ./testdir2
cp ./test001.in ./testdir2/.test001.in
mkdir ./testdir2/testdir2_dir1
cp ./test000.in ./testdir2/testdir2_dir1
cp ./test001.in ./testdir2/testdir2_dir1
mkdir ./testdir2/testdir2_dir2
mkdir ./testdir2/testdir2_dir1/testdir2_dir1_dir1
mkdir ./testdir2/testdir2_dir1/testdir2_dir1_dir2
mkdir ./testdir2/testdir2_dir1/testdir2_dir1_dir1/testdir2_dir1_dir1_dir1
cp ./test000.in ./testdir2/testdir2_dir1/testdir2_dir1_dir1/testdir2_dir1_dir1_dir1
cp ./test001.in  ./testdir2/testdir2_dir2
ln -s $path/testdir2 ./testdir2/testdir2_dir1/testdir2_dir1_dir1/testdir2_dir1_dir1_dir1/symtest1
ln -s noexit ./testdir2/testdir2_dir1/testdir2_dir1_dir1/testdir2_dir1_dir1_dir1/symtest2
mkdir ./testdir2/testdir2_dir2/testdir2_dir2_dir1
mkdir ./testdir2/testdir2_dir2/testdir2_dir2_dir2
cp ./test000.in ./testdir2/testdir2_dir2/testdir2_dir2_dir1
cp ./test001.in ./testdir2/testdir2_dir2/testdir2_dir2_dir2

echo "The test directory structure"
find ./testdir1 -print | sed -e '/^\.$/d' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
echo
find ./testdir2 -print | sed -e '/^\.$/d' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
echo 
echo
echo
#rm -rf testdir1
#rm -rf testdir2
make clean